name: SWG
channels:
  - defaults
dependencies:
  - numpy
  - xarray
  - scipy
  - conda-forge::cfgrib
  - matplotlib
  - cftime
  - nbclient
  - nbconvert
  - pyyaml
  - netcdf4
  - h5netcdf
