Simulation name: 'Test Region'
Simulation Start Year: 1990
Simulation End Year: 2100
Number of Simulations: 1
ERA5 Directory: 'C:\Users\Username\ERA\'
Regenerate Data: False
Data Output Directory: 'C:\Users\Username\SWG\'
Lat Bounds: [-38.2, -39.6]
Lon Bounds: [175.3, 176.4]
Variable Adjust: True
Non-stationary Mode: False
